apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-trace-generator
  labels:
    app: k6-trace-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-trace-generator
  template:
    metadata:
      labels:
        app: k6-trace-generator
    spec:
      containers:
      - name: k6-trace-generator
        image: ghcr.io/grafana/xk6-client-tracing:v0.0.7 #This extension provides k6 with the required functionality required to load test distributed tracing backends.
        env:
        - name: ENDPOINT
          value: "alloy:4317" #Alloy is an agent for collecting telemetry data. It supports OpenTelemetry and can receive traces via OTLP. &. sends them to tempo for storage and querying.
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always


      
---
apiVersion: v1      
kind: Service
metadata:
  name: k6-trace-generator
  namespace: monitoring
spec:
  selector:
    app: k6-trace-generator
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP